#pragma once

#include <SDL3/SDL_keyboard.h>
#include <SDL3/SDL_stdinc.h>

#include <cstdint>
#include <ranges>
#include <type_traits>

#include "slickdl.hpp"
#include "slickdl/line_box.hpp"
#include "slickdl/properties.hpp"
#include "slickdl/scancode.hpp"

namespace slickdl::keyboard {

// The SDL virtual key representation.
//
// Values of this type are used to represent keyboard keys using the current
// layout of the keyboard. These values include Unicode values representing
// the unmodified character that would be generated by pressing the key, or an
// `SDLK_*` constant for those keys that do not generate characters.
//
// A special exception is the number keys at the top of the keyboard which map
// to SDLK_0...SDLK_9 on AZERTY layouts.
//
// Keys with the `SDLK_EXTENDED_MASK` bit set do not map to a scancode or
// unicode code point.
using code_t = enum class code : uint32_t {
    unknown = 0x00000000U,          /**< 0 */
    enter = 0x0000000dU,            /**< '\r' */
    escape = 0x0000001bU,           /**< '\x1B' */
    backspace = 0x00000008U,        /**< '\b' */
    tab = 0x00000009U,              /**< '\t' */
    space = 0x00000020U,            /**< ' ' */
    exclaim = 0x00000021U,          /**< '!' */
    doubleApostrophe = 0x00000022U, /**< '"' */
    hash = 0x00000023U,             /**< '#' */
    dollar = 0x00000024U,           /**< '$' */
    percent = 0x00000025U,          /**< '%' */
    ampersand = 0x00000026U,        /**< '&' */
    apostrophe = 0x00000027U,       /**< '\'' */
    leftParenthesis = 0x00000028U,  /**< '(' */
    rightParenthesis = 0x00000029U, /**< ')' */
    asterisk = 0x0000002aU,         /**< '*' */
    plus = 0x0000002bU,             /**< '+' */
    comma = 0x0000002cU,            /**< ',' */
    minus = 0x0000002dU,            /**< '-' */
    period = 0x0000002eU,           /**< '.' */
    slash = 0x0000002fU,            /**< '/' */
    number0 = 0x00000030U,          /**< '0' */
    number1 = 0x00000031U,          /**< '1' */
    number2 = 0x00000032U,          /**< '2' */
    number3 = 0x00000033U,          /**< '3' */
    number4 = 0x00000034U,          /**< '4' */
    number5 = 0x00000035U,          /**< '5' */
    number6 = 0x00000036U,          /**< '6' */
    number7 = 0x00000037U,          /**< '7' */
    number8 = 0x00000038U,          /**< '8' */
    number9 = 0x00000039U,          /**< '9' */
    colon = 0x0000003aU,            /**< ':' */
    semicolon = 0x0000003bU,        /**< ';' */
    less = 0x0000003cU,             /**< '<' */
    equals = 0x0000003dU,           /**< '=' */
    greater = 0x0000003eU,          /**< '>' */
    question = 0x0000003fU,         /**< '?' */
    at = 0x00000040U,               /**< '@' */
    leftBracket = 0x0000005bU,      /**< '[' */
    backslash = 0x0000005cU,        /**< '\\' */
    rightBracket = 0x0000005dU,     /**< ']' */
    caret = 0x0000005eU,            /**< '^' */
    underscore = 0x0000005fU,       /**< '_' */
    grave = 0x00000060U,            /**< '`' */
    a = 0x00000061U,                /**< 'a' */
    b = 0x00000062U,                /**< 'b' */
    c = 0x00000063U,                /**< 'c' */
    d = 0x00000064U,                /**< 'd' */
    e = 0x00000065U,                /**< 'e' */
    f = 0x00000066U,                /**< 'f' */
    g = 0x00000067U,                /**< 'g' */
    h = 0x00000068U,                /**< 'h' */
    i = 0x00000069U,                /**< 'i' */
    j = 0x0000006aU,                /**< 'j' */
    k = 0x0000006bU,                /**< 'k' */
    l = 0x0000006cU,                /**< 'l' */
    m = 0x0000006dU,                /**< 'm' */
    n = 0x0000006eU,                /**< 'n' */
    o = 0x0000006fU,                /**< 'o' */
    p = 0x00000070U,                /**< 'p' */
    q = 0x00000071U,                /**< 'q' */
    r = 0x00000072U,                /**< 'r' */
    s = 0x00000073U,                /**< 's' */
    t = 0x00000074U,                /**< 't' */
    u = 0x00000075U,                /**< 'u' */
    v = 0x00000076U,                /**< 'v' */
    w = 0x00000077U,                /**< 'w' */
    x = 0x00000078U,                /**< 'x' */
    y = 0x00000079U,                /**< 'y' */
    z = 0x0000007aU,                /**< 'z' */
    leftBrace = 0x0000007bU,        /**< '{' */
    pipe = 0x0000007cU,             /**< '|' */
    rightBrace = 0x0000007dU,       /**< '}' */
    tilde = 0x0000007eU,            /**< '~' */
    erase = 0x0000007fU,            /**< '\x7F' */
    plusMinus = 0x000000b1U,        /**< '\xB1' */
    capsLock =
        0x40000039U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CAPSLOCK) */
    f1 = 0x4000003aU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F1) */
    f2 = 0x4000003bU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F2) */
    f3 = 0x4000003cU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F3) */
    f4 = 0x4000003dU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F4) */
    f5 = 0x4000003eU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F5) */
    f6 = 0x4000003fU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F6) */
    f7 = 0x40000040U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F7) */
    f8 = 0x40000041U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F8) */
    f9 = 0x40000042U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F9) */
    f10 = 0x40000043U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F10) */
    f11 = 0x40000044U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F11) */
    f12 = 0x40000045U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F12) */
    printScreen =
        0x40000046U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRINTSCREEN) */
    scrollLock =
        0x40000047U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SCROLLLOCK) */
    pause = 0x40000048U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAUSE) */
    insert = 0x40000049U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_INSERT) */
    home = 0x4000004aU,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HOME) */
    pageup = 0x4000004bU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEUP) */
    end = 0x4000004dU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_END) */
    pageDown =
        0x4000004eU,     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PAGEDOWN) */
    right = 0x4000004fU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RIGHT) */
    left = 0x40000050U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LEFT) */
    down = 0x40000051U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DOWN) */
    up = 0x40000052U,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UP) */
    numlockClear =
        0x40000053U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_NUMLOCKCLEAR) */
    kpDivide =
        0x40000054U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DIVIDE) */
    kpMultiply =
        0x40000055U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MULTIPLY) */
    kpMinus =
        0x40000056U,      /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MINUS) */
    kpPlus = 0x40000057U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUS) */
    kpEnter =
        0x40000058U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_ENTER) */
    kp1 = 0x40000059U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_1) */
    kp2 = 0x4000005aU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_2) */
    kp3 = 0x4000005bU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_3) */
    kp4 = 0x4000005cU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_4) */
    kp5 = 0x4000005dU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_5) */
    kp6 = 0x4000005eU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_6) */
    kp7 = 0x4000005fU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_7) */
    kp8 = 0x40000060U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_8) */
    kp9 = 0x40000061U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_9) */
    kp0 = 0x40000062U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_0) */
    kpPeriod =
        0x40000063U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERIOD) */
    application =
        0x40000065U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_APPLICATION) */
    power = 0x40000066U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_POWER) */
    kpEquals =
        0x40000067U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALS) */
    f13 = 0x40000068U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F13) */
    f14 = 0x40000069U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F14) */
    f15 = 0x4000006aU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F15) */
    f16 = 0x4000006bU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F16) */
    f17 = 0x4000006cU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F17) */
    f18 = 0x4000006dU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F18) */
    f19 = 0x4000006eU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F19) */
    f20 = 0x4000006fU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F20) */
    f21 = 0x40000070U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F21) */
    f22 = 0x40000071U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F22) */
    f23 = 0x40000072U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F23) */
    f24 = 0x40000073U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_F24) */
    execute = 0x40000074U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXECUTE) */
    help = 0x40000075U,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_HELP) */
    menu = 0x40000076U,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MENU) */
    select = 0x40000077U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SELECT) */
    stop = 0x40000078U,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_STOP) */
    again = 0x40000079U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AGAIN) */
    undo = 0x4000007aU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_UNDO) */
    cut = 0x4000007bU,     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CUT) */
    copy = 0x4000007cU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_COPY) */
    paste = 0x4000007dU,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PASTE) */
    find = 0x4000007eU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_FIND) */
    mute = 0x4000007fU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MUTE) */
    volumeup =
        0x40000080U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEUP) */
    volumedown =
        0x40000081U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_VOLUMEDOWN) */
    kpComma =
        0x40000085U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COMMA) */
    kpEqualsaS400 =
        0x40000086U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EQUALSAS400)
                      */
    alterase =
        0x40000099U,      /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ALTERASE) */
    sysreq = 0x4000009aU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SYSREQ) */
    cancel = 0x4000009bU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CANCEL) */
    clear = 0x4000009cU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEAR) */
    prior = 0x4000009dU,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_PRIOR) */
    returN2 = 0x4000009eU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RETURN2) */
    separator =
        0x4000009fU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SEPARATOR) */
    out = 0x400000a0U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OUT) */
    oper = 0x400000a1U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_OPER) */
    clearAgain =
        0x400000a2U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CLEARAGAIN) */
    crsel = 0x400000a3U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CRSEL) */
    exsel = 0x400000a4U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_EXSEL) */
    kp00 = 0x400000b0U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_00) */
    kp000 = 0x400000b1U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_000) */
    thousandsSeparator =
        0x400000b2U, /**<
                        SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_THOUSANDSSEPARATOR)
                      */
    decimalseparator =
        0x400000b3U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_DECIMALSEPARATOR)
                      */
    currencyunit =
        0x400000b4U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYUNIT) */
    currencysubunit =
        0x400000b5U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CURRENCYSUBUNIT)
                      */
    kpLeftBracket =
        0x400000b6U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTPAREN) */
    kpRightBracket =
        0x400000b7U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTPAREN) */
    kpLeftbrace =
        0x400000b8U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LEFTBRACE) */
    kpRightbrace =
        0x400000b9U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_RIGHTBRACE) */
    kpTab = 0x400000baU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_TAB) */
    kpBackspace =
        0x400000bbU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BACKSPACE) */
    kpA = 0x400000bcU,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_A) */
    kpB = 0x400000bdU,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_B) */
    kpC = 0x400000beU,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_C) */
    kpD = 0x400000bfU,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_D) */
    kpE = 0x400000c0U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_E) */
    kpF = 0x400000c1U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_F) */
    kpXor = 0x400000c2U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_XOR) */
    kpPower =
        0x400000c3U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_POWER) */
    kpPercent =
        0x400000c4U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PERCENT) */
    kpLess = 0x400000c5U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_LESS) */
    kpGreater =
        0x400000c6U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_GREATER) */
    kpAmpersand =
        0x400000c7U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AMPERSAND) */
    kpDoubleAmpersand =
        0x400000c8U, /**<
                      * SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DoubleAMPERSAND)
                      */
    kpVerticalbar =
        0x400000c9U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_VERTICALBAR)
                      */
    kpDoubleVerticalbar =
        0x400000caU, /**<
                     SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DoubleVERTICALBAR)
                   */
    kpColon =
        0x400000cbU,      /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_COLON) */
    kpHash = 0x400000ccU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HASH) */
    kpSpace =
        0x400000cdU,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_SPACE) */
    kpAt = 0x400000ceU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_AT) */
    kpExclam =
        0x400000cfU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_EXCLAM) */
    kpMemstore =
        0x400000d0U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSTORE) */
    kpMemrecall =
        0x400000d1U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMRECALL) */
    kpMemclear =
        0x400000d2U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMCLEAR) */
    kpMemadd =
        0x400000d3U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMADD) */
    kpMemsubtract =
        0x400000d4U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMSUBTRACT)
                      */
    kpMemmultiply =
        0x400000d5U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMMULTIPLY)
                      */
    kpMemdivide =
        0x400000d6U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_MEMDIVIDE) */
    kpPlusminus =
        0x400000d7U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_PLUSMINUS) */
    kpClear =
        0x400000d8U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEAR) */
    kpClearentry =
        0x400000d9U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_CLEARENTRY) */
    kpBinary =
        0x400000daU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_BINARY) */
    kpOctal =
        0x400000dbU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_OCTAL) */
    kpDecimal =
        0x400000dcU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_DECIMAL) */
    kpHexadecimal =
        0x400000ddU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_KP_HEXADECIMAL)
                      */
    leftCtrl = 0x400000e0U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LCTRL) */
    leftShift =
        0x400000e1U,       /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LSHIFT) */
    leftAlt = 0x400000e2U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LALT) */
    // TODO: Rename
    leftGUI = 0x400000e3U,   /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_LGUI) */
    rightCtrl = 0x400000e4U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RCTRL) */
    rightShift =
        0x400000e5U,        /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RSHIFT) */
    rightAlt = 0x400000e6U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RALT) */
    rgui = 0x400000e7U,     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_RGUI) */
    mode = 0x40000101U,     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MODE) */
    sleep = 0x40000102U,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SLEEP) */
    wake = 0x40000103U,     /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_WAKE) */
    channelIncrement =
        0x40000104U, /**<
                        SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_INCREMENT)
                      */
    channelDecrement =
        0x40000105U, /**<
                        SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CHANNEL_DECREMENT)
                      */
    mediaPlay =
        0x40000106U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY) */
    mediaPause =
        0x40000107U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PAUSE) */
    mediaRecord =
        0x40000108U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_RECORD) */
    mediaFastForward =
        0x40000109U, /**<
                        SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_FAST_FORWARD)
                      */
    mediaRewind =
        0x4000010aU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_REWIND) */
    mediaNextTrack =
        0x4000010bU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_NEXT_TRACK)
                      */
    mediaPreviousTrack =
        0x4000010cU, /**<
                        SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PREVIOUS_TRACK)
                      */
    mediaStop =
        0x4000010dU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_STOP) */
    mediaEject =
        0x4000010eU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_EJECT) */
    mediaPlayPause =
        0x4000010fU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_PLAY_PAUSE)
                      */
    mediaSelect =
        0x40000110U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_MEDIA_SELECT) */
    acNew = 0x40000111U,  /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_NEW) */
    acOpen = 0x40000112U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_OPEN) */
    acClose =
        0x40000113U,      /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_CLOSE) */
    acExit = 0x40000114U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_EXIT) */
    acSave = 0x40000115U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SAVE) */
    acPrint =
        0x40000116U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PRINT) */
    acProperties =
        0x40000117U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_PROPERTIES) */
    acSearch =
        0x40000118U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_SEARCH) */
    acHome = 0x40000119U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_HOME) */
    acBack = 0x4000011aU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BACK) */
    acForward =
        0x4000011bU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_FORWARD) */
    acStop = 0x4000011cU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_STOP) */
    acRefresh =
        0x4000011dU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_REFRESH) */
    acBookmarks =
        0x4000011eU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_AC_BOOKMARKS) */
    softLeft =
        0x4000011fU, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTLEFT) */
    softRight =
        0x40000120U,    /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_SOFTRIGHT) */
    call = 0x40000121U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_CALL) */
    endCall = 0x40000122U, /**< SDL_SCANCODE_TO_KEYCODE(SDL_SCANCODE_ENDCALL) */
    leftTab = 0x20000001U, /**< Extended key Left Tab */
    leveL5Shift = 0x20000002U,     /**< Extended key Level 5 Shift */
    multiKeyCompose = 0x20000003U, /**< Extended key Multi-key Compose */
    leftMeta = 0x20000004U,        /**< Extended key Left Meta */
    rightMeta = 0x20000005U,       /**< Extended key Right Meta */
    leftHyper = 0x20000006U,       /**< Extended key Left Hyper */
    rightHyper = 0x20000007U,      /**< Extended key Right Hyper */
};

using codeUnderlying_t = std::underlying_type_t< code_t >;

[[nodiscard]] constexpr auto toLegacy( code_t _code ) -> SDL_Keycode {
    return ( static_cast< SDL_Keycode >( _code ) );
}

[[nodiscard]] constexpr auto toLegacy( code_t* _code ) -> SDL_Keycode* {
    return ( std::bit_cast< SDL_Keycode* >( _code ) );
}

[[nodiscard]] constexpr auto fromLegacy( SDL_Keycode _code ) -> code_t {
    return ( static_cast< code_t >( _code ) );
}

// Valid key modifiers (possibly OR'd together).
using modifier_t = enum class modifier : uint16_t {
    none = 0U,          /**< no modifier is applicable. */
    leftShift = 0x1U,   /**< the left Shift key is down. */
    rightShift = 0x2U,  /**< the right Shift key is down. */
    level5Shift = 0x4U, /**< the Level 5 Shift key is down. */
    leftCtrl = 0x40U,   /**< the left Ctrl (Control) key is down. */
    rightCtrl = 0x80U,  /**< the right Ctrl (Control) key is down. */
    leftAlt = 0x100U,   /**< the left Alt key is down. */
    rightAlt = 0x200U,  /**< the right Alt key is down. */
    leftMeta = 0x400U, /**< the left GUI key (often the Windows key) is down. */
    rightMeta =
        0x800U, /**< the right GUI key (often the Windows key) is down. */
    numLock = 0x1000U,  /**< the Num Lock key (may be located on an extended
                       keypad)  is down. */
    capsLock = 0x2000U, /**< the Caps Lock key is down. */
    // TODO: Rename
    mode = 0x4000U,       /**< the !AltGr key is down. */
    scrollLock = 0x8000U, /**< the Scroll Lock key is down. */

    // Generalized
    ctrl = ( leftCtrl | rightCtrl ),    /**< Any Ctrl key is down. */
    shift = ( leftShift | rightShift ), /**< Any Shift key is down. */
    alt = ( leftAlt | rightAlt ),       /**< Any Alt key is down. */
    meta = ( leftMeta | rightMeta ),    /**< Any GUI key is down. */
};

using modifierUnderlying_t = std::underlying_type_t< modifier_t >;

[[nodiscard]] constexpr auto toLegacy( modifier_t _modifier ) -> SDL_Keymod {
    return ( static_cast< SDL_Keymod >( _modifier ) );
}

[[nodiscard]] constexpr auto toLegacy( modifier_t* _modifier ) -> SDL_Keymod* {
    return ( std::bit_cast< SDL_Keymod* >( _modifier ) );
}

[[nodiscard]] constexpr auto fromLegacy( SDL_Keymod _modifier ) -> modifier_t {
    return ( static_cast< modifier_t >( _modifier ) );
}

// This is a unique ID for a keyboard for the time it is connected to the
// system, and is never reused for the lifetime of the application.
//
// If the keyboard is disconnected and reconnected, it will get a new ID.
//
// The value 0 is an invalid ID.
using id_t = size_t;

// Return whether a keyboard is currently connected.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto any() -> bool {
    return ( SDL_HasKeyboard() );
}

// Get a list of currently connected keyboards.
//
// Note that this will include any device or virtual driver that includes
// keyboard functionality, including some mice, KVM switches, motherboard
// power buttons, etc. You should wait for input from a device before you
// consider it actively in use.
//
// Should only be called on the main thread.
[[nodiscard]] auto all() -> std::vector< id_t >;

// Get the name of a keyboard.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto name( id_t _id )
    -> std::optional< std::string_view > {
    const char* l_result = SDL_GetKeyboardNameForID( _id );

    assert( l_result );

    std::string_view l_returnValue = l_result;

    if ( l_returnValue.empty() ) {
        return ( std::nullopt );

    } else {
        return ( l_returnValue );
    }
}

// Query the window which currently has keyboard focus.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto focus() -> slickdl::window_t {
    return ( SDL_GetKeyboardFocus() );
}

// Get a snapshot of the current state of the keyboard.
//
// The pointer returned is a pointer to an internal SDL array. It will be
// valid for the whole lifetime of the application and should not be freed
// by the caller.
//
// A array element with a value of true means that the key is pressed and a
// value of false means that it is not. Indexes into this array are obtained
// by using SDL_Scancode values.
//
// Use SDL_PumpEvents() to update the state array.
//
// This function gives you the current state after all events have been
// processed, so if a key or button has been pressed and released before you
// process events, then the pressed state will never show up in the
// SDL_GetKeyboardState() calls.
//
// Note: This function doesn't take into account whether shift has been
// pressed or not.
// TODO: Improve
[[nodiscard]] auto state()
    -> std::array< bool, static_cast< size_t >( scancode_t::count ) >;

// Clear the state of the keyboard.
//
// This function will generate key up events for all pressed keys.
//
// Should only be called on the main thread.
inline void reset() {
    SDL_ResetKeyboard();
}

// Get the current key modifier state for the keyboard.
[[nodiscard]] inline auto modifier() -> modifier_t {
    return ( static_cast< modifier_t >( SDL_GetModState() ) );
}

// Set the current key modifier state for the keyboard.
//
// The inverse of SDL_GetModState(), SDL_SetModState() allows you to impose
// modifier key states on your application. Simply pass your desired
// modifier states into `modstate`. This value may be a bitwise, OR'd
// combination of SDL_Keymod values.
//
// This does not change the keyboard state, only the key modifier flags that
// SDL reports.
inline void modifier( modifier_t _modifier ) {
    SDL_SetModState( toLegacy( _modifier ) );
}

// Get the key code corresponding to the given scancode according to the
// current keyboard layout.
//
// If you want to get the keycode as it would be delivered in key events,
// including options specified in SDL_HINT_KEYCODE_OPTIONS, then you should
// pass `key_event` as true. Otherwise this function simply translates the
// scancode based on the given modifier state.
//
// Modifier state to use when translating the scancode
// to a keycode.
//
// If the keycode will be used in key events.
//
// Not thread safe.
[[nodiscard]] inline auto keyFromScancode( scancode_t _scancode,
                                           modifier_t _modstate,
                                           bool _keyEvent ) -> code_t {
    return ( static_cast< code_t >( SDL_GetKeyFromScancode(
        toLegacy( _scancode ), toLegacy( _modstate ), _keyEvent ) ) );
}

// Get the scancode corresponding to the given key code according to the
// current keyboard layout.
//
// Note that there may be multiple scancode+modifier states that can
// generate this keycode, this will just return the first one found.
//
// The modifier state that would be used when the scancode generates this key,
// may be NULL.
//
// Not thread safe.
[[nodiscard]] inline auto scancodeFromKey(
    code_t _code,
    std::optional< modifier_t > _modifier = std::nullopt ) -> scancode_t {
    if ( _modifier ) {
        return ( static_cast< scancode_t >( SDL_GetScancodeFromKey(
            toLegacy( _code ), toLegacy( &_modifier.value() ) ) ) );

    } else {
        return ( static_cast< scancode_t >(
            SDL_GetScancodeFromKey( toLegacy( _code ), nullptr ) ) );
    }
}

// Set a human-readable name for a scancode.
//
// Name must be encoded as UTF-8. The string is not copied, so the pointer given
// to this function must stay valid while SDL is being used.
//
// Not thread safe.
inline void scancodeName( scancode_t _scancode, std::string_view _name ) {
    const bool l_result = SDL_SetScancodeName( toLegacy( _scancode ),
                                               std::string( _name ).c_str() );

    assert( l_result );
}

// Get a human-readable name for a scancode.
//
// **Warning**: The returned name is by design not stable across platforms,
// e.g. the name for `SDL_SCANCODE_LGUI` is "Left GUI" under Linux but "Left
// Windows" under Microsoft Windows, and some scancodes like
// `SDL_SCANCODE_NONUSBACKSLASH` don't have any name at all. There are even
// scancodes that share names, e.g. `SDL_SCANCODE_RETURN` and
// `SDL_SCANCODE_RETURN2` (both called "Return"). This function is therefore
// unsuitable for creating a stable cross-platform two-way mapping between
// strings and scancodes.
//
// Not thread safe.
[[nodiscard]] inline auto scancodeName( scancode_t _scancode )
    -> std::string_view {
    const std::string_view l_result =
        SDL_GetScancodeName( toLegacy( _scancode ) );

    assert( !l_result.empty() );

    return ( l_result );
}

// Get a scancode from a human-readable name.
//
// Not thread safe.
[[nodiscard]] inline auto scancodeFromName( std::string_view _name )
    -> scancode_t {
    const scancode_t l_result = static_cast< scancode_t >(
        SDL_GetScancodeFromName( std::string( _name ).c_str() ) );

    assert( l_result != scancode_t::unknown );

    return ( l_result );
}

// Get a human-readable name for a key.
//
// If the key doesn't have a name, this function asserts.
//
// Letters will be presented in their uppercase form, if applicable.
//
// Not thread safe.
[[nodiscard]] inline auto keyName( code_t _code ) -> std::string_view {
    const std::string_view l_result = SDL_GetKeyName( toLegacy( _code ) );

    assert( !l_result.empty() );

    return ( l_result );
}

// Get a key code from a human-readable name.
//
// Not thread safe.
[[nodiscard]] inline auto keyFromName( std::string_view _name ) -> code_t {
    const code_t l_result = static_cast< code_t >(
        SDL_GetKeyFromName( std::string( _name ).c_str() ) );

    assert( l_result != code_t::unknown );

    return ( l_result );
}

namespace text_input {

// Start accepting Unicode text input events in a window.
//
// This function will enable text input (SDL_EVENT_TEXT_INPUT and
// SDL_EVENT_TEXT_EDITING events) in the specified window. Please use this
// function paired with SDL_StopTextInput().
//
// Text input events are not received by default.
//
// On some platforms using this function shows the screen keyboard and/or
// activates an IME, which can prevent some key press events from being
// passed through.
//
// Should only be called on the main thread.
inline void start( window_t _window ) {
    const bool l_result = SDL_StartTextInput( _window );

    assert( l_result );
}

// Text input type.
//
// These are the valid values for SDL_PROP_TEXTINPUT_TYPE_NUMBER. Not every
// value is valid on every platform, but where a value isn't supported, a
// reasonable fallback will be used.
using textInput_t = enum class textInput : uint8_t {
    text,                  /**< The input is text */
    textName,              /**< The input is a person's name */
    textEmail,             /**< The input is an e-mail address */
    textUsername,          /**< The input is a username */
    textPasswordHidden,    /**< The input is a secure
                                                   password   that is hidden */
    textPasswordVisible,   /**< The input is a secure
                                                   password that is visible */
    number,                /**< The input is a number */
    numberPasswordHidden,  /**< The input is a secure
                                                   PIN that is hidden */
    numberPasswordVisible, /**< The input is a secure
                                                  PIN that is visible */
};

// Auto capitalization type.
//
// These are the valid values for SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER.
// Not every value is valid on every platform, but where a value isn't
// supported, a reasonable fallback will be used.
using capitalization_t = enum class capitalization : uint8_t {
    none,      /**< No auto-capitalization will be done */
    sentences, /**< The first letter of sentences will be
                                 capitalized */
    words,     /**< The first letter of words will be capitalized
                */
    letters,   /**< All letters will be capitalized */
};

// Start accepting Unicode text input events in a window, with properties
// describing the input.
//
// This function will enable text input (SDL_EVENT_TEXT_INPUT and
// SDL_EVENT_TEXT_EDITING events) in the specified window. Please use this
// function paired with SDL_StopTextInput().
//
// Text input events are not received by default.
//
// On some platforms using this function shows the screen keyboard and/or
// activates an IME, which can prevent some key press events from being
// passed through.
//
// These are the supported properties:
//
// - `SDL_PROP_TEXTINPUT_TYPE_NUMBER` - an SDL_TextInputType value that
//   describes text being input, defaults to SDL_TEXTINPUT_TYPE_TEXT.
// - `SDL_PROP_TEXTINPUT_CAPITALIZATION_NUMBER` - an SDL_Capitalization
// value that describes how text should be capitalized, defaults to
//   SDL_CAPITALIZE_SENTENCES for normal text entry, SDL_CAPITALIZE_WORDS
// for SDL_TEXTINPUT_TYPE_TEXT_NAME, and SDL_CAPITALIZE_NONE for e-mail
//   addresses, usernames, and passwords.
// - `SDL_PROP_TEXTINPUT_AUTOCORRECT_BOOLEAN` - true to enable auto
// completion and auto correction, defaults to true.
// - `SDL_PROP_TEXTINPUT_MULTILINE_BOOLEAN` - true if multiple lines of text
//   are allowed. This defaults to true if SDL_HINT_RETURN_KEY_HIDES_IME is
//   "0" or is not set, and defaults to false if
// SDL_HINT_RETURN_KEY_HIDES_IME is "1".
//
// On Android you can directly specify the input type:
//
// - `SDL_PROP_TEXTINPUT_ANDROID_INPUTTYPE_NUMBER` - the text input type to
//   use, overriding other properties. This is documented at
//   https://developer.android.com/reference/android/text/InputType
//
// Should only be called on the main thread.
inline void start( window_t _window, properties::id_t _properties ) {
    const bool l_result =
        SDL_StartTextInputWithProperties( _window, _properties );

    assert( l_result );
}

constexpr std::string_view g_typeNumber = "SDL.textinput.type";
constexpr std::string_view g_capitalizationNumber =
    "SDL.textinput.capitalization";
constexpr std::string_view g_autocorrectBoolean = "SDL.textinput.autocorrect";
constexpr std::string_view g_multilineBoolean = "SDL.textinput.multiline";
constexpr std::string_view g_androidInputtypeNumber =
    "SDL.textinput.android.inputtype";

// Check whether or not Unicode text input events are enabled for a window.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto isActive( window_t _window ) -> bool {
    return ( SDL_TextInputActive( _window ) );
}

// Stop receiving any text input events in a window.
//
// If SDL_StartTextInput() showed the screen keyboard, this function will
// hide it.
//
// Should only be called on the main thread.
inline void stop( window_t _window ) {
    const bool l_result = SDL_StopTextInput( _window );

    assert( l_result );
}

// Dismiss the composition window/IME without disabling the subsystem.
//
// Should only be called on the main thread.
inline void clearComposition( window_t _window ) {
    const bool l_result = SDL_ClearComposition( _window );

    assert( l_result );
}

// Set the area used to type Unicode text input.
//
// Native input methods may place a window with word suggestions near the
// cursor, without covering the text being entered.
//
// The text input area, in window coordinates, or NULL to clear it.
//
// The offset of the current cursor location relative to `box->x`, in window
// coordinates.
//
// Should only be called on the main thread.
inline void area( window_t _window,
                  const std::optional< box_t< int > >& _box,
                  ssize_t _cursor ) {
    bool l_result = false;

    if ( _box ) {
        const SDL_Rect l_box = _box.value();

        l_result = SDL_SetTextInputArea( _window, &l_box, _cursor );

    } else {
        l_result = SDL_SetTextInputArea( _window, nullptr, _cursor );
    }

    assert( l_result );
}

// Get the area used to type Unicode text input.
//
// This returns the values previously set by SDL_SetTextInputArea().
//
// The text input area, in window coordinates, may be NULL.
//
// The offset of the current cursor location relative to `box->x`, in window
// coordinates.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto area( window_t _window )
    -> std::pair< box_t< int >, ssize_t > {
    box_t< int > l_box;
    ssize_t l_cursor = 0;

    const bool l_result =
        SDL_GetTextInputArea( _window, std::bit_cast< SDL_Rect* >( &l_box ),
                              std::bit_cast< int* >( &l_cursor ) );

    assert( l_result );

    return { l_box, l_cursor };
}

} // namespace text_input

// Check whether the platform has screen keyboard support.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto hasScreenKeyboard() -> bool {
    return ( SDL_HasScreenKeyboardSupport() );
}

// Check whether the screen keyboard is shown for given window.
//
// Should only be called on the main thread.
[[nodiscard]] inline auto isScreenKeyboardActive( window_t _window ) -> bool {
    return ( SDL_ScreenKeyboardShown( _window ) );
}

constexpr size_t g_extendedCodeMask = ( 1U << 29 );

[[nodiscard]] constexpr auto scancodeToKeycode( scancode_t _scancode )
    -> code_t {
    constexpr size_t l_scancodeMask = ( 1U << 30 );

    return ( static_cast< code_t >( toLegacy( _scancode ) | l_scancodeMask ) );
}

} // namespace slickdl::keyboard
